autorun:
  block: true
formatter:
- clippy: {}
tools:
  hadolint:
    ignore:
    - DL3008
    - DL3010
    - DL3012
    - DL3018
    - DL3020
    - DL3022
    - DL3027
    - DL4001
    run: true
  r2c.registry.latest:
    ignore: []
    run: true
